configs:
  create_db_sql:
    content: |
      CREATE DATABASE kuboard DEFAULT CHARACTER SET = 'utf8mb4' DEFAULT COLLATE = 'utf8mb4_unicode_ci';
      create user 'kuboard'@'%' identified by 'kuboardpwd';
      grant all privileges on kuboard.* to 'kuboard'@'%';
      FLUSH PRIVILEGES;

services:
  kuboard-ldap-example:
    image: swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard-v4-ldap-example:v4
    environment:
      - LDAP_URL=ldap://x.x.x.x:389
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_USERNAME=cn=ww,dc=example,dc=com
      - LDAP_PASSWORD=example@2025
      - LDAP_BASE=ou=People,dc=example,dc=com
    volumes:
      - /data/app/kuboard_v4/kuboard-v4-ldap-example.jar:/app/kuboard-v4-ldap-example.jar
    networks:
      kuboard_v4_ldap_example:
        aliases:
          - ldap-example
  db:
    image: docker.m.daocloud.io/mariadb:11.2.2-jammy
    environment:
      MARIADB_ROOT_PASSWORD: kuboardpwd
      MYSQL_ROOT_PASSWORD: kuboardpwd
      TZ: Asia/Shanghai
    volumes:
      - ./data/kuboard-mariadb:/var/lib/mysql:Z
    configs:
      - source: create_db_sql
        target: /docker-entrypoint-initdb.d/create_db.sql
        mode: 0777
    networks:
      kuboard_v4_ldap_example:
        aliases:
          - db
  kuboard:
    image: swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard:v4.0.0.1
    environment:
      - DB_DRIVER=org.mariadb.jdbc.Driver
      - DB_URL=jdbc:mariadb://db:3306/kuboard?serverTimezone=Asia/Shanghai
      - DB_USERNAME=kuboard
      - DB_PASSWORD=kuboardpwd
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      kuboard_v4_ldap_example:
        aliases:
          - kuboard

networks:
  kuboard_v4_ldap_example:
    driver: bridge
