server:
  port: 9090

spring:
  application:
    name: kuboard-v4-example-user-repository
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Shanghai
  ldap:
    urls: ${LDAP_URL:ldap://172.18.0.184:389}
    username: ${LDAP_USERNAME:cn=winway,dc=winwayworld,dc=com}
    password: ${LDAP_PASSWORD:winway@2025}
    base: ${LDAP_BASE:ou=People,dc=winwayworld,dc=com}
logging:
  level:
    org.springframework.ldap: DEBUG
    com.sun.jndi.ldap: DEBUG